import { MAP_IMAGE_RECT } from './constants';

// Khattalwada's alignment was hand-calibrated (see useCalibration's "Calibrate
// map" mode) before this per-village-rect.json convention existed, so it has
// no companion "-rect.json" file. Every other village falls back to null
// (no background image) until one is generated by scripts/extract_plot_map.py.
const KHATTALWADA_KEY = 'Khattalwada Rev 3.1 New Village Mapping A0 part1';

// Villages are whatever plot JSON files have been dropped under src/assets -
// scanned broadly (not tied to one folder name) since files have ended up
// scattered across a few differently-named subfolders.
const plotModules = import.meta.glob([
  '../../assets/**/*.json',
  '!../../assets/**/*-rect.json',
  '!../../assets/**/*-labels-review.json',
]);
const imageModules = import.meta.glob('../../assets/**/*.png', { eager: true, import: 'default' });
const rectModules = import.meta.glob('../../assets/**/*-rect.json', { eager: true, import: 'default' });

function keyOf(path, suffix) {
  const name = path.split('/').pop().replace(/\.(json|png)$/i, '');
  return name.endsWith(suffix) ? name.slice(0, -suffix.length) : name;
}

// Source filenames are long survey-sheet titles (e.g. "Ahu Rev 3.2-NEW
// VILLAGE MAPPING A1") - trim down to just the village name for display.
function prettyName(key) {
  const match = key.match(/^(.*?)[\s_-]*rev\s*\d/i);
  return (match ? match[1] : key).trim();
}

const imagesByKey = new Map(
  Object.entries(imageModules).map(([path, url]) => [keyOf(path, '-map'), url])
);
const rectsByKey = new Map(
  Object.entries(rectModules).map(([path, rect]) => [keyOf(path, '-rect'), rect])
);

// `path` is relative to this file (src/plot-map/helpers/villages.js), two
// directories below the project root - rewriting its "../../" prefix to
// "src/" gives the project-root-relative path the save-plots dev server
// middleware (see vite.config.ts) needs to write edits back to the right file.
function toProjectPath(path) {
  return path.replace(/^(\.\.\/)+/, 'src/');
}

export const VILLAGES = Object.entries(plotModules)
  .map(([path, load]) => {
    const key = keyOf(path, '-plots');
    return {
      key,
      label: prettyName(key),
      loadPlots: () => load().then((m) => m.default),
      plotsPath: toProjectPath(path),
      imageUrl: imagesByKey.get(key) ?? null,
      imageRect: rectsByKey.get(key) ?? (key === KHATTALWADA_KEY ? MAP_IMAGE_RECT : null),
    };
  })
  .sort((a, b) => a.label.localeCompare(b.label));
